#!/usr/bin/env python3
"""Generate navigation-oriented Markdown from the canonical YAML catalogue."""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from collections.abc import Sequence
from pathlib import Path

from scripts.catalog import ROOT, load_taxonomy, load_tools, write_if_changed

GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_docs.py; do not edit directly. -->"
)


def label_map(items: list[dict[str, str]]) -> dict[str, str]:
    return {item["id"]: item["name"] for item in items}


def markdown_list(values: list[str], fallback: str) -> str:
    rendered = values or [fallback]
    return "\n".join(f"- {item}" for item in rendered)


def tool_links(tool: dict[str, object]) -> str:
    links = []
    for field, label in (
        ("official_url", "Official site"),
        ("documentation_url", "Documentation"),
        ("repository_url", "Source repository"),
    ):
        if value := tool.get(field):
            links.append(f"[{label}]({value})")
    return " · ".join(links)


def render_tool(
    tool: dict[str, object],
    categories: dict[str, str],
    roles: dict[str, str],
) -> str:
    category_names = ", ".join(categories[item] for item in tool["categories"])
    role_names = ", ".join(roles[item] for item in tool["roles"])
    metadata_lines = [
        f"**Categories:** {category_names}",
        f"**Roles:** {role_names}",
        f"**Model:** {str(tool['license_model']).replace('-', ' ').title()}",
        f"**Status:** {str(tool['status']).replace('-', ' ').title()}",
    ]
    if tool.get("repository_archived"):
        metadata_lines.append("**Repository:** Archived")
    use_fallback = (
        "Use after confirming that the documented capability matches a concrete "
        "operational requirement."
    )
    avoid_fallback = (
        "Consider alternatives until primary-source, licence, and maintenance "
        "verification is complete for your risk profile."
    )
    return "\n".join(
        [
            f"### {tool['name']}",
            "",
            "<br>\n".join(metadata_lines),
            "",
            str(tool["summary"]),
            "",
            "**Use when**",
            "",
            markdown_list(tool.get("use_when", []), use_fallback),
            "",
            "**Consider alternatives when**",
            "",
            markdown_list(tool.get("avoid_when", []), avoid_fallback),
            "",
            tool_links(tool),
            "",
        ]
    )


def render_category(
    category: dict[str, str],
    tools: list[dict[str, object]],
    categories: dict[str, str],
    roles: dict[str, str],
) -> str:
    selected = sorted(
        (tool for tool in tools if category["id"] in tool["categories"]),
        key=lambda tool: str(tool["name"]).casefold(),
    )
    body = [
        GENERATED_NOTICE,
        f"# {category['name']}",
        "",
        f"{len(selected)} canonical records reference this category.",
        "",
        "[Back to catalogue](../../README.md)",
        "",
    ]
    body.extend(render_tool(tool, categories, roles) for tool in selected)
    return "\n".join(body).rstrip() + "\n"


def render_role(
    role: dict[str, str],
    tools: list[dict[str, object]],
    categories: dict[str, str],
) -> str:
    selected = sorted(
        (tool for tool in tools if role["id"] in tool["roles"]),
        key=lambda tool: str(tool["name"]).casefold(),
    )
    rows = [
        GENERATED_NOTICE,
        f"# {role['name']}",
        "",
        f"{len(selected)} tools and resources are indexed for this role.",
        "",
        "| Tool | Categories | Model | Status |",
        "|---|---|---|---|",
    ]
    for tool in selected:
        url = tool.get("official_url") or tool.get("repository_url")
        category_names = ", ".join(categories[item] for item in tool["categories"])
        rows.append(
            f"| [{tool['name']}]({url}) | {category_names} | "
            f"{tool['license_model']} | {tool['status']} |"
        )
    rows.extend(["", "[Back to catalogue](../../README.md)", ""])
    return "\n".join(rows)


def render_lifecycle(stage: str, tools: list[dict[str, object]]) -> str:
    selected = sorted(
        (tool for tool in tools if stage in tool["lifecycle_stages"]),
        key=lambda tool: str(tool["name"]).casefold(),
    )
    rows = [
        GENERATED_NOTICE,
        f"# {stage.title()} lifecycle",
        "",
        f"{len(selected)} records support this lifecycle stage.",
        "",
    ]
    rows.extend(
        f"- [{tool['name']}]({tool.get('official_url') or tool.get('repository_url')}) — {tool['summary']}"
        for tool in selected
    )
    rows.extend(["", "[Back to catalogue](../../README.md)", ""])
    return "\n".join(rows)


def render_index(title: str, items: list[dict[str, str]], directory: str) -> str:
    rows = [GENERATED_NOTICE, f"# {title}", ""]
    rows.extend(f"- [{item['name']}]({item['id']}.md)" for item in items)
    rows.extend(["", "[Back to catalogue](../../README.md)", ""])
    return "\n".join(rows)


def render_lifecycle_index(stages: list[str]) -> str:
    rows = [GENERATED_NOTICE, "# Lifecycle index", ""]
    rows.extend(f"- [{stage.title()}]({stage}.md)" for stage in stages)
    rows.extend(["", "[Back to catalogue](../../README.md)", ""])
    return "\n".join(rows)


def render_deprecated(tools: list[dict[str, object]]) -> str:
    selected = [
        tool
        for tool in tools
        if tool["status"] in {"deprecated", "archived", "historical"}
        or "deprecated-historical" in tool["categories"]
    ]
    rows = [
        GENERATED_NOTICE,
        "# Deprecated and historical tools",
        "",
        "Records remain here for migration and historical context; they are not active recommendations.",
        "",
    ]
    if selected:
        rows.extend(
            f"- **{tool['name']}** ({tool['status']}) — {tool['summary']}"
            for tool in selected
        )
    else:
        rows.append(
            "No records have yet completed the primary-source review required for this classification."
        )
    rows.append("")
    return "\n".join(rows)


def render_reconciliation(root: Path) -> str:
    with (root / "migration" / "reconciliation.csv").open(
        encoding="utf-8", newline=""
    ) as handle:
        rows = list(csv.DictReader(handle))
    dispositions = Counter(row["disposition"] for row in rows)
    inventory = json.loads(
        (root / "migration" / "source-inventory.json").read_text(encoding="utf-8")
    )
    stale = [item["path"] for item in inventory if "stale" in item["disposition"]]
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Archive reconciliation",
            "",
            "Every parsed legacy occurrence has a row in `migration/reconciliation.csv`.",
            "",
            "| Disposition | Occurrences |",
            "|---|---:|",
            *(f"| {name} | {count} |" for name, count in sorted(dispositions.items())),
            "",
            f"**Total source occurrences:** {len(rows)}  ",
            f"**Stale generated inputs:** {', '.join(stale)}",
            "",
            "The migration uses normalized primary URLs first, then versioned aliases in "
            "`config/import-overrides.yaml`. A merged occurrence keeps its original file, "
            "line, name, and URL in the reconciliation ledger and canonical record provenance.",
            "",
        ]
    )


def render_root(taxonomy: dict[str, object], tools: list[dict[str, object]]) -> str:
    categories = taxonomy["categories"]
    roles = taxonomy["roles"]
    stages = taxonomy["lifecycle_stages"]
    model_counts = Counter(tool["license_model"] for tool in tools)
    status_counts = Counter(tool["status"] for tool in tools)
    last_generated = max(str(tool["verified_on"]) for tool in tools)
    category_counts = Counter(
        category for tool in tools for category in tool["categories"]
    )
    rows = [
        GENERATED_NOTICE,
        "# DevOps Tools Catalogue",
        "",
        "A comprehensive, curated, and continuously maintained catalogue for DevOps, cloud, "
        "platform, SRE, DevSecOps, infrastructure, Kubernetes, FinOps, observability, release, "
        "developer-experience, and MLOps practitioners.",
        "",
        "> The YAML under `data/` is authoritative. Generated Markdown is navigation, not a second source of truth.",
        "",
        "## Catalogue status",
        "",
        f"- **Canonical records:** {len(tools)}",
        f"- **Categories:** {len(categories)}",
        f"- **Records requiring review:** {sum(bool(tool.get('needs_review')) for tool in tools)}",
        f"- **Archived repositories:** {sum(bool(tool.get('repository_archived')) for tool in tools)}",
        f"- **Last generation date:** {last_generated}",
        "- **Maintenance status:** Active migration; unverified metadata is explicitly marked.",
        "",
        "## Start with a task",
        "",
        "| I need to... | Start here |",
        "|---|---|",
        "| Build a Kubernetes platform | [Kubernetes operations](docs/categories/kubernetes-distributions-operations.md) |",
        "| Choose an IaC stack | [IaC decision guide](docs/decision-guides/terraform-opentofu-pulumi.md) |",
        "| Build a secure CI/CD pipeline | [Supply-chain security](docs/categories/software-supply-chain-security.md) |",
        "| Observe Kubernetes | [Monitoring and tracing](docs/categories/monitoring-metrics-logs-tracing.md) |",
        "| Assemble an OSS-first stack | [Default stacks](docs/default-stacks.md#oss-first-environment) |",
        "| Work with Azure, AWS, or GCP | [Cloud platforms](docs/categories/cloud-platforms-management.md) |",
        "| Build a homelab | [Virtualization and homelab](docs/categories/virtualization-bare-metal-homelab.md) |",
        "| Build an MLOps platform | [MLOps and AI infrastructure](docs/categories/mlops-llmops-ai-infrastructure.md) |",
        "| Add FinOps controls | [FinOps and sustainability](docs/categories/finops-sustainability.md) |",
        "",
        "## Category index",
        "",
        "| Category | Records |",
        "|---|---:|",
    ]
    rows.extend(
        f"| [{item['name']}](docs/categories/{item['id']}.md) | {category_counts[item['id']]} |"
        for item in categories
    )
    rows.extend(["", "## Browse by role", ""])
    rows.extend(f"- [{item['name']}](docs/roles/{item['id']}.md)" for item in roles)
    rows.extend(["", "## Browse by lifecycle", ""])
    rows.extend(f"- [{stage.title()}](docs/lifecycle/{stage}.md)" for stage in stages)
    rows.extend(
        [
            "",
            "## Licence-model legend",
            "",
            "| Model | Meaning | Records |",
            "|---|---|---:|",
            f"| `oss` | Source claims an OSI-approved licence; verify SPDX before adoption. | {model_counts['oss']} |",
            f"| `source-available` | Source is visible under a non-OSI or restricted licence. | {model_counts['source-available']} |",
            f"| `open-core` | OSS/community core with commercial features or service. | {model_counts['open-core']} |",
            f"| `commercial` | Proprietary commercial product. | {model_counts['commercial']} |",
            f"| `free-saas` | Hosted service with a free offering. | {model_counts['free-saas']} |",
            f"| `documentation` | Learning or documentation resource. | {model_counts['documentation']} |",
            f"| `unknown` | Reliable licence evidence has not been recorded. | {model_counts['unknown']} |",
            "",
            "## Project-status legend",
            "",
            "| Status | Meaning | Records |",
            "|---|---|---:|",
            *(
                f"| `{status}` | {description} | {status_counts[status]} |"
                for status, description in (
                    (
                        "active",
                        "Maintained according to recorded primary-source evidence.",
                    ),
                    ("needs-review", "Imported but not yet fully verified."),
                    ("deprecated", "Superseded or discouraged by its maintainer."),
                    ("archived", "Repository or product is archived."),
                    ("historical", "Retained for context or migration work."),
                )
            ),
            "",
            "## Recommendations and decisions",
            "",
            "- [Default stacks](docs/default-stacks.md)",
            "- [Decision guides](docs/decision-guides/README.md)",
            "- [Deprecated and historical tools](docs/deprecated-tools.md)",
            "",
            "## Contributing and methodology",
            "",
            "Read [CONTRIBUTING.md](CONTRIBUTING.md) before proposing a tool. The "
            "[methodology](docs/methodology.md) explains inclusion, verification, provenance, "
            "and lifecycle rules. Run `python -m scripts.generate_docs` after changing YAML, "
            "then `python -m scripts.validate_catalog` before opening a pull request.",
            "",
            "Security concerns belong in [SECURITY.md](SECURITY.md), not a public issue.",
            "",
        ]
    )
    return "\n".join(rows)


def expected_outputs(root: Path = ROOT) -> dict[Path, str]:
    taxonomy = load_taxonomy(root)
    tools = load_tools(root)
    categories = label_map(taxonomy["categories"])
    roles = label_map(taxonomy["roles"])
    outputs: dict[Path, str] = {
        root / "README.md": render_root(taxonomy, tools),
        root / "docs" / "categories" / "README.md": render_index(
            "Category index", taxonomy["categories"], "categories"
        ),
        root / "docs" / "roles" / "README.md": render_index(
            "Role index", taxonomy["roles"], "roles"
        ),
        root / "docs" / "lifecycle" / "README.md": render_lifecycle_index(
            taxonomy["lifecycle_stages"]
        ),
        root / "docs" / "deprecated-tools.md": render_deprecated(tools),
        root / "docs" / "archive-reconciliation.md": render_reconciliation(root),
    }
    for category in taxonomy["categories"]:
        outputs[root / "docs" / "categories" / f"{category['id']}.md"] = (
            render_category(category, tools, categories, roles)
        )
    for role in taxonomy["roles"]:
        outputs[root / "docs" / "roles" / f"{role['id']}.md"] = render_role(
            role, tools, categories
        )
    for stage in taxonomy["lifecycle_stages"]:
        outputs[root / "docs" / "lifecycle" / f"{stage}.md"] = render_lifecycle(
            stage, tools
        )
    statistics = {
        "canonical_records": len(tools),
        "categories": len(taxonomy["categories"]),
        "license_models": dict(
            sorted(Counter(tool["license_model"] for tool in tools).items())
        ),
        "statuses": dict(sorted(Counter(tool["status"] for tool in tools).items())),
    }
    outputs[root / "docs" / "catalog-statistics.json"] = (
        json.dumps(statistics, indent=2, sort_keys=True) + "\n"
    )
    return outputs


def generate(root: Path = ROOT, check: bool = False) -> list[str]:
    drift: list[str] = []
    for path, content in expected_outputs(root).items():
        relative = path.relative_to(root).as_posix()
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(relative)
        else:
            write_if_changed(path, content)
    return drift


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    drift = generate(args.root.resolve(), check=args.check)
    if drift:
        print("Generated documentation is stale:")
        print("\n".join(f"- {path}" for path in drift))
        return 1
    print("Generated documentation is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
