#!/usr/bin/env python3
"""Generate and verify the pinned Python constraints used by CI."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import tempfile
import tomllib
import venv
from collections.abc import Iterable, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONSTRAINTS = ROOT / "config" / "python-constraints-3.12.txt"
EXTRA_BUILD_REQUIREMENTS = ["editables"]
EXCLUDED_PACKAGES = {
    "devops-tools-catalog",
    "pip",
    "setuptools",
    "wheel",
}
NAME_NORMALIZER = re.compile(r"[-_.]+")


def canonicalize_name(name: str) -> str:
    return NAME_NORMALIZER.sub("-", name).lower()


def parse_pinned_requirements(lines: Iterable[str]) -> dict[str, str]:
    requirements: dict[str, str] = {}
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, version = line.partition("==")
        if not separator or not version:
            raise ValueError(f"expected pinned requirement, got: {raw_line!r}")
        canonical_name = canonicalize_name(name)
        if canonical_name in EXCLUDED_PACKAGES:
            continue
        requirements[canonical_name] = version
    return dict(sorted(requirements.items()))


def render_constraints(requirements: dict[str, str]) -> str:
    header = (
        "# Generated by `python -m scripts.python_constraints --write`.\n"
        "# Pinned for the Python 3.12 CI environment.\n"
    )
    body = "\n".join(f"{name}=={version}" for name, version in requirements.items())
    return f"{header}\n{body}\n"


def diff_constraints(
    expected: dict[str, str], actual: dict[str, str]
) -> tuple[list[str], list[str], list[str]]:
    missing = [name for name in expected if name not in actual]
    added = [name for name in actual if name not in expected]
    changed = [
        name for name in expected if name in actual and expected[name] != actual[name]
    ]
    return missing, added, changed


def _venv_python(venv_dir: Path) -> Path:
    if os.name == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def load_build_requirements(root: Path = ROOT) -> list[str]:
    pyproject = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    requires = pyproject["build-system"]["requires"]
    return [*map(str, requires), *EXTRA_BUILD_REQUIREMENTS]


def _run(command: Sequence[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        text=True,
        capture_output=True,
        check=True,
    )


def resolve_constraints(root: Path = ROOT) -> dict[str, str]:
    with tempfile.TemporaryDirectory(prefix="catalog-python-constraints-") as tmp:
        venv_dir = Path(tmp) / "venv"
        venv.EnvBuilder(with_pip=True).create(venv_dir)
        python = _venv_python(venv_dir)
        _run(
            [
                str(python),
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-input",
                *load_build_requirements(root),
            ],
            cwd=root,
        )
        _run(
            [
                str(python),
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-input",
                "--no-build-isolation",
                "-e",
                ".[dev]",
            ],
            cwd=root,
        )
        freeze = _run(
            [str(python), "-m", "pip", "freeze", "--exclude-editable"],
            cwd=root,
        )
    return parse_pinned_requirements(freeze.stdout.splitlines())


def write_constraints(path: Path, root: Path = ROOT) -> int:
    constraints = resolve_constraints(root)
    path.write_text(render_constraints(constraints), encoding="utf-8")
    print(f"Wrote {path.relative_to(root)} with {len(constraints)} pinned packages.")
    return 0


def check_constraints(path: Path, root: Path = ROOT) -> int:
    expected = parse_pinned_requirements(path.read_text(encoding="utf-8").splitlines())
    actual = resolve_constraints(root)
    missing, added, changed = diff_constraints(expected, actual)
    if not any((missing, added, changed)):
        print(f"Python constraints match {path.relative_to(root)}.")
        return 0

    print(f"Python dependency drift detected against {path.relative_to(root)}:")
    for name in missing:
        print(f"- missing: {name}=={expected[name]}")
    for name in added:
        print(f"- added: {name}=={actual[name]}")
    for name in changed:
        print(f"- changed: {name} expected {expected[name]} resolved {actual[name]}")
    print("Refresh with: python -m scripts.python_constraints --write")
    return 1


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--constraints-file",
        type=Path,
        default=DEFAULT_CONSTRAINTS,
        help="Path to the committed constraints file.",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    constraints_path = args.constraints_file.resolve()
    constraints_path.parent.mkdir(parents=True, exist_ok=True)
    if args.write:
        return write_constraints(constraints_path)
    return check_constraints(constraints_path)


if __name__ == "__main__":
    raise SystemExit(main())
